name = "SSKit"
uuid = "274e52f3-f6d1-4e8f-9534-18824e48e2ad"
authors = ["Sagar Saxena <sagsxn@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
